version: "3.9"  
services:
  redis-server:
    image: "redis:alpine"
  pointinside:
    build: ./
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - redis-server
